models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property integer $id
 * @property string $email
 * @property string $email_confirm_token
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $first_name
 * @property string $last_name
 * @property integer $student_group_id
 * @property integer $student_subgroup
 * @property integer $role
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_BLOCKED = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_WAIT = 2;

    const ROLE_GUEST = 0;
    const ROLE_UNCONFIRMED_USER = 1;
    const ROLE_USER = 5;
    const ROLE_TRUSTED = 10;
    const ROLE_CAPTAIN = 50;
    const ROLE_ADMIN = 100;

    const SEX_FEMALE = 1;
    const SEX_MALE = 2;
    
    const SUBGROUP_ALL = 0;
    const SUBGROUP_1 = 1;
    const SUBGROUP_2 = 2;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email', 'auth_key', 'password_hash', 'first_name', 'last_name',], 'required'],
            [['student_group_id', 'student_subgroup', 'role', 'status', ], 'integer'],
            [['email', 'email_confirm_token', 'password_hash', 'password_reset_token', 'first_name', 'last_name'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['email'], 'unique'],
            [['email_confirm_token'], 'unique'],
            [['password_reset_token'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'USER_ID'),
            'email' => Yii::t('app', 'USER_EMAIL'),
            'first_name' => Yii::t('app', 'USER_FIRST_NAME'),
            'last_name' => Yii::t('app', 'USER_LAST_NAME'),
            'student_group_id' => Yii::t('app', 'USER_STUDENT_GROUP_ID'),
            'student_subgroup' => Yii::t('app', 'USER_STUDENT_SUBGROUP'),
            'role' => Yii::t('app', 'Role'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'fullName' => Yii::t('app', 'USER_FULL_NAME'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentGroup()
    {
        return $this->hasOne(StudentGroup::className(), ['id' => 'student_group_id']);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('findIdentityByAccessToken is not implemented.');
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Finds user by Email
     *
     * @param string $email
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }


    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }
    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @param integer $timeout
     * @return static|null
     */
    public static function findByPasswordResetToken($token, $timeout)
    {
        if (!static::isPasswordResetTokenValid($token, $timeout)) {
            return null;
        }
        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @param integer $timeout
     * @return bool
     */
    public static function isPasswordResetTokenValid($token, $timeout)
    {
        if (empty($token)) {
            return false;
        }
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        return $timestamp + $timeout >= time();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * @param string $email_confirm_token
     * @return static|null
     */
    public static function findByEmailConfirmToken($email_confirm_token)
    {
        return static::findOne(['email_confirm_token' => $email_confirm_token, 'status' => self::STATUS_WAIT]);
    }

    /**
     * Generates email confirmation token
     */
    public function generateEmailConfirmToken()
    {
        $this->email_confirm_token = Yii::$app->security->generateRandomString();
    }

    /**
     * Removes email confirmation token
     */
    public function removeEmailConfirmToken()
    {
        $this->email_confirm_token = null;
    }

    public function getFullName() { 
        return $this->first_name . ' ' . $this->last_name;
    }

    public static function getRoles() {
        return [
            self::ROLE_GUEST => 'Гость',
            self::ROLE_UNCONFIRMED_USER => 'Неактивированный',
            self::ROLE_USER => 'Пользователь',
            self::ROLE_TRUSTED => 'Доверенный',
            self::ROLE_CAPTAIN => 'Староста',
            self::ROLE_ADMIN => 'аДмИн',
        ];
    }

    public function getTextRole() {
        return self::getRoles()[$this->role];
    }
    
    public static function getListStudentSubgroup($withAll = false) {
        $result = [];
        if ($withAll) {
            $result[self::SUBGROUP_ALL] = 'Общее';
        }
        $result += [
            self::SUBGROUP_1 => 'Первая подгруппа',
            self::SUBGROUP_2 => 'Вторая подгруппа',
        ];
        return $result;
    }
    public static function getValuesStudentSubgroup($withAll = false) {
        $result = [];
        if ($withAll) {
            $result[] = self::SUBGROUP_ALL;
        }
        $result += [
            self::SUBGROUP_1,
            self::SUBGROUP_2,
        ];
        return $result;
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\Account;
use app\models\form\LoginForm;
use app\models\form\PasswordResetForm;
use app\models\form\PasswordResetRequestForm;
use app\models\form\SignupForm;
use app\models\form\EmailConfirmForm;
use app\models\User;
use Yii;
use yii\authclient\ClientInterface;
use yii\authclient\clients\VKontakte;
use yii\base\InvalidParamException;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

class UserController extends Controller
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['signup', 'error', 'auth', 'login', 'email-confirm', 'password-reset-request', 'password-reset', 'success-callback'],
                        'allow' => true,
                        'roles' => ['guest'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['admin', 'change-role'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
            ],
        ];
    }

    public function actionAdmin()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
        ]);

        return $this->render('admin', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function successCallback(ClientInterface $client)
    {
        $attributes = $client->getUserAttributes();
        $client_id = null;
        if ($client instanceof VKontakte) {
            $client_id = $attributes['user_id'];
        }
        $account = Account::find()->where(['client' => $client->getId(), 'client_id' => $client_id])->one();
        if ($account) {
            /**
             * @var Account $account
             */
            if ($account->user_id != 0) {
                $user = User::findIdentity($account->user_id);
                if ($user)
                    Yii::$app->user->login($user, 3600 * 24 * 30);
                return $this->goBack();
            } else {
                return $this->redirect(['/user/signup', 'connection' => $account->connection_string]);
            }


        } else {
            $account = new Account();
            $account->client = $client->id;
            $account->client_id = $attributes['user_id'];
            $account->client_data = serialize($attributes);
            $account->user_id = 0;
            $account->connection_string = Yii::$app->security->generateRandomString();
            $account->status = Account::STATUS_WAIT;
            if ($account->save()) {
                return $this->redirect(['/user/signup', 'connection' => $account->connection_string]);
            }
        }
        return $this->redirect(['/user/login']);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionSignup()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new SignupForm(Yii::$app->request->get('connection', null));
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'FLASH_EMAIL_CONFIRM_REQUEST'));
                return $this->goHome();
            }
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionEmailConfirm($token)
    {
        try {
            $model = new EmailConfirmForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($model->confirmEmail()) {
            Yii::$app->getSession()->setFlash('success', Yii::t('app', 'FLASH_EMAIL_CONFIRM_SUCCESS'));
        } else {
            Yii::$app->getSession()->setFlash('error', Yii::t('app', 'FLASH_EMAIL_CONFIRM_ERROR'));
        }
        return $this->goHome();
    }

    public function actionPasswordResetRequest()
    {
        $model = new PasswordResetRequestForm(\Yii::$app->params['passwordResetTokenExpire']);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', Yii::t('app', 'FLASH_PASSWORD_RESET_REQUEST'));
                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', Yii::t('app', 'FLASH_PASSWORD_RESET_ERROR'));
            }
        }
        return $this->render('passwordResetRequest', [
            'model' => $model,
        ]);
    }

    public function actionPasswordReset($token)
    {
        try {
            $model = new PasswordResetForm($token, \Yii::$app->params['passwordResetTokenExpire']);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', Yii::t('app', 'FLASH_PASSWORD_RESET_SUCCESS'));
            return $this->goHome();
        }
        return $this->render('passwordReset', [
            'model' => $model,
        ]);
    }

    public function actionChangeRole($id, $role)
    {
        $user = User::find()->where([
            'id' => $id,
        ])->one();
        if (!$user)
            return $this->redirect('/admin/user/');
        /**
         * @var User $user
         */
        if (in_array($role, [
            User::ROLE_UNCONFIRMED_USER,
            User::ROLE_USER,
            User::ROLE_TRUSTED,
            User::ROLE_CAPTAIN,
        ])) {
            $user->role = $role;
            $user->save();
        }

        return $this->redirect('/user/admin');
    }
}

views/user/admin.php
<?php

use app\models\User;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="student-group-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'fullName',
            'studentGroup.number',
            'student_subgroup',
            [
                'class' => 'yii\grid\DataColumn',
                'attribute' => 'role',
                'value' => 'textRole',
            ],


            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{activation} {deactivation} {make_trusted} {make_captain} {make_user}',
                'buttons' => [
                    'activation' => function ($url, $model, $key) {
                        /**
                         * @var User $model
                         */
                        $options = [
                            'title' => 'Активировать',
                            'aria-label' => 'Активировать',
                            'data-confirm' => 'Вы действительно хотите активировать ' . $model->getFullName() . ' (' . $model->email . ')',
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ];
                        $url = Url::toRoute(['/user/change-role', 'id' => $model->id, 'role' => User::ROLE_USER]);
                        $html = Html::a('<span class="glyphicon glyphicon-ok"></span>', $url, $options);
                        return ($model->role == User::ROLE_UNCONFIRMED_USER) ? $html : '';
                    },
                    'deactivation' => function ($url, $model, $key) {
                        /**
                         * @var User $model
                         */
                        $options = [
                            'title' => 'Деактивировать',
                            'aria-label' => 'Деактивировать',
                            'data-confirm' => 'Вы действительно хотите деактивировать ' . $model->getFullName() . ' (' . $model->email . ')',
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ];
                        $url = Url::toRoute(['/user/change-role', 'id' => $model->id, 'role' => User::ROLE_UNCONFIRMED_USER]);
                        $html = Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, $options);
                        return ($model->role == User::ROLE_USER) ? $html : '';
                    },
                    'make_trusted' => function ($url, $model, $key) {
                        /**
                         * @var User $model
                         */
                        $options = [
                            'title' => 'Сделать пользователя Доверенным?',
                            'aria-label' => 'Сделать пользователя Доверенным?',
                            'data-confirm' => 'Вы действительно хотите сделать пользователя ' . $model->getFullName() . ' (' . $model->email . ')  доверенным ?',
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ];
                        $url = Url::toRoute(['/user/change-role', 'id' => $model->id, 'role' => User::ROLE_TRUSTED]);
                        $html = Html::a('<span class="glyphicon glyphicon-sunglasses"></span>', $url, $options);
                        return ($model->role == User::ROLE_USER || $model->role == User::ROLE_CAPTAIN) ? $html : '';
                    },
                    'make_captain' => function ($url, $model, $key) {
                        /**
                         * @var User $model
                         */
                        $options = [
                            'title' => 'Сделать пользователя Старостой?',
                            'aria-label' => 'Сделать пользователя Старостой?',
                            'data-confirm' => 'Вы действительно хотите сделать пользователя ' . $model->getFullName() . ' (' . $model->email . ')  старостой ?',
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ];
                        $url = Url::toRoute(['/user/change-role', 'id' => $model->id, 'role' => User::ROLE_CAPTAIN]);
                        $html = Html::a('<span class="glyphicon glyphicon-knight"></span>', $url, $options);
                        return ($model->role == User::ROLE_USER || $model->role == User::ROLE_TRUSTED) ? $html : '';
                    },
                    'make_user' => function ($url, $model, $key) {
                        /**
                         * @var User $model
                         */
                        $options = [
                            'title' => 'Сделать пользователем?',
                            'aria-label' => 'Сделать пользователем?',
                            'data-confirm' => 'Вы действительно хотите сделать ' . $model->getFullName() . ' (' . $model->email . ') пользователем ?',
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ];
                        $url = Url::toRoute(['/user/change-role', 'id' => $model->id, 'role' => User::ROLE_USER]);
                        $html = Html::a('<span class="glyphicon glyphicon-user"></span>', $url, $options);
                        return ($model->role == User::ROLE_TRUSTED || $model->role == User::ROLE_CAPTAIN) ? $html : '';
                    },
                ],
            ],
        ],
    ]); ?>

</div>

views/user/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>
    

</div>

views/user/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\form\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>
    <div class="well">
        <div class="col-lg-offset-1 col-lg-11"> <?= yii\authclient\widgets\AuthChoice::widget([
                'baseAuthUrl' => ['user/auth'],
                'popupMode' => false,
            ]) ?>
        </div>
        <?php $form = ActiveForm::begin([
            'id' => 'login-form',
            'options' => ['class' => 'form-horizontal'],
            'fieldConfig' => [
                'template' => "<div class=\"col-lg-offset-1 col-lg-4\"><div class=\"label-floating\">{label}\n{input}</div></div>\n<div class=\"col-lg-7\">{error}</div>",
                'labelOptions' => ['class' => 'control-label'],
            ],
        ]); ?>

        <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\"><div class=\"checkbox\"><label>{input} {labelTitle}</label></div></div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::a(Yii::t('app', 'LINK_PASSWORD_RESET'), ['password-reset-request']) ?>.
        </div>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton(Yii::t('app', 'Login'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/user/passwordChange.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \app\models\form\PasswordChangeForm */

$this->title = Yii::t('app', 'TITLE_PASSWORD_CHANGE');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'TITLE_PROFILE'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-profile-password-change">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="user-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'currentPassword')->passwordInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'newPassword')->passwordInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'newPasswordRepeat')->passwordInput(['maxlength' => true]) ?>

        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'BUTTON_SAVE'), ['class' => 'btn btn-primary', 'name' => 'change-button']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

views/user/passwordReset.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\form\PasswordResetForm */

$this->title = Yii::t('app', 'TITLE_PASSWORD_RESET');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-default-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('app', 'PLEASE_FILL_FOR_RESET') ?></p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'password-reset-form']); ?>
            <?= $form->field($model, 'password')->passwordInput() ?>
            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'reset-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/user/passwordResetRequest.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\form\PasswordResetRequestForm */

$this->title = Yii::t('app', 'TITLE_PASSWORD_RESET');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-default-password-reset-request">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?= Yii::t('app', 'PLEASE_FILL_FOR_RESET_REQUEST') ?></p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'password-reset-request-form']); ?>
            <?= $form->field($model, 'email') ?>
            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'BUTTON_SEND'), ['class' => 'btn btn-primary', 'name' => 'reset-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/user/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\form\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Signup');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <div class="well">
        <?php $form = ActiveForm::begin([
            'id' => 'form-signup',
            'options' => ['class' => 'form-horizontal'],
            'fieldConfig' => [
                'template' => "<div class=\"col-lg-offset-1 col-lg-4\"><div class=\"label-floating\">{label}\n{input}</div></div>\n<div class=\"col-lg-7\">{error}</div>",
                'labelOptions' => ['class' => 'control-label'],
            ],
        ]); ?>

        <?= $form->field($model, 'email')->textInput() ?>

        <?= $form->field($model, 'password')->passwordInput() ?>
        <?= $form->field($model, 'firstName')->textInput() ?>
        <?= $form->field($model, 'lastName')->textInput() ?>


        <?= $form->field($model, 'studentGroupId')->dropDownList(\app\models\StudentGroup::getList()) ?>
        <?= $form->field($model, 'studentSubgroup')->dropDownList(\app\models\User::getListStudentSubgroup()) ?>

        <?= $form->field($model, 'reCaptcha')->widget(\himiklab\yii2\recaptcha\ReCaptcha::className()) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton(Yii::t('app', 'SIGNUP_BUTTON'), ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>